source 'https://rubygems.org'

gem 'watir-webdriver'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'require_all'
gem 'headless'
gem 'markaby'
gem 'nokogiri', '1.6.7'
gem 'rake'
gem 'rest-client'
gem 'rspec-expectations'
gem 'pry'
gem 'mail'

 gem 'dbi'
 gem 'dbd-mysql'
