source 'https://rubygems.org'

gem 'watir-webdriver'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'require_all'
gem 'headless'
gem 'markaby'
gem 'nokogiri', '1.6.6.2'
gem 'rake'
gem 'rest-client'
#gem 'dbi'
#gem 'dbd-mysql'
